#! /bin/sh

# exit on error:
set -e

git checkout gh-pages

rm -f *.html
rm -rf media

mv _build/* .
rm -r _build

git add *.html
git add media

git commit -a -m "Automatic commit"
git checkout master
